retargeting:
  type: DexPilot
  urdf_path: tesollo_hand/tesollo_hand_left.urdf

  # Target refers to the retargeting target, which is the robot hand
  wrist_link_name: "delto_base_link"
  finger_tip_link_names: [ "F1_TIP", "F2_TIP", "F3_TIP" ]
  scaling_factor: 1.0

  # A smaller alpha means stronger filtering, i.e. more smooth but also larger latency
  low_pass_alpha: 0.2
